/* サイトの名前と全作品をここで管理します。追加方法はREADME.mdを参照してください。 */
window.EXHIBITION = {
  name: "ソフトメディア研究会",
  year: "2026",
  festivalName: "津田沼祭 ゲーム作品展",
  message: "操作や展示について不明な点は、会場のスタッフにお尋ねください。",
  sampleMode: true,
};

window.GAMES = [
  {
    id: "game01",
    title: "MOSSBOUND",
    subtitle: "森の遺跡を探索する2Dアクション",
    icon: "./assets/images/games/mossbound.svg",
    iconAlt: "光る森の遺跡にたたずむ、小さな白い旅人のイラスト",
    description: "旅人を操作して森の遺跡を探索する2Dアクションゲームです。足場を飛び越えながら、光のかけらを集めます。",
    genre: "アクション",
    players: "1人",
    playTime: "5〜10分",
    platform: "Windows PC",
    creators: ["ゲーム制作チーム A"],
    team: "Team Moss",
    accent: "#e3f1e7",
    tip: "ジャンプ中も左右に移動できます。足場の端からジャンプしてください。",
    controls: [
      { device: "キーボード", items: [{ keys: ["A", "D", "←", "→"], action: "左右に移動" }, { keys: ["Space"], action: "ジャンプ" }, { keys: ["E"], action: "調べる・話しかける" }, { keys: ["Esc"], action: "ポーズ・メニュー" }] },
      { device: "ゲームパッド", items: [{ keys: ["左スティック"], action: "左右に移動" }, { keys: ["A ボタン"], action: "ジャンプ" }, { keys: ["X ボタン"], action: "調べる・話しかける" }, { keys: ["Menu"], action: "ポーズ・メニュー" }] },
    ],
    screenshots: [
      { src: "./assets/images/games/mossbound-scene-1.svg", alt: "光る植物と大きな門がある、はじまりの森", caption: "森の探索画面" },
      { src: "./assets/images/games/mossbound-scene-2.svg", alt: "水面に浮かぶ足場と、光のかけらがある遺跡", caption: "足場を使った移動" },
      { src: "./assets/images/games/mossbound-scene-3.svg", alt: "大樹の前で輝く光を見つけた旅人", caption: "光のかけらの収集" },
    ],
    video: { type: "local", src: "./assets/videos/mossbound-preview.mp4", poster: "./assets/images/games/mossbound-scene-1.svg", caption: "サンプル映像（6秒・音声なし）。オリジナルイラストによる展示イメージです。" },
  },
  {
    id: "game02",
    title: "ORBIT SHIFT",
    subtitle: "ステージを回転させて解く立体パズル",
    icon: "./assets/images/games/orbit-shift.svg",
    iconAlt: "紫の宇宙空間に浮かぶ、ミント色と白色の立方体のパズル",
    description: "ステージを回転させて移動経路を探す立体パズルゲームです。ブロックのつながりを確認し、キューブをゴールまで移動させます。",
    genre: "パズル",
    players: "1人",
    playTime: "3〜5分",
    platform: "PC / スマートフォン",
    creators: ["ゲーム制作チーム B"],
    team: "Orbit Works",
    accent: "#eeebf8",
    tip: "移動経路が見つからない場合は、ステージを回転させて確認してください。手数の制限はありません。",
    controls: [
      { device: "マウス", items: [{ keys: ["ドラッグ"], action: "ステージを回転" }, { keys: ["左クリック"], action: "行き先のブロックを選ぶ" }, { keys: ["右クリック"], action: "ひとつ前に戻る" }] },
      { device: "スマートフォン", items: [{ keys: ["スワイプ"], action: "ステージを回転" }, { keys: ["タップ"], action: "行き先のブロックを選ぶ" }, { keys: ["戻るボタン"], action: "ひとつ前に戻る" }] },
    ],
    screenshots: [
      { src: "./assets/images/games/orbit-shift-scene-1.svg", alt: "星空に浮かぶ立体パズルの最初のステージ", caption: "最初のステージ" },
      { src: "./assets/images/games/orbit-shift-scene-2.svg", alt: "離れた立方体をつないで進むパズルステージ", caption: "ブロックの移動経路" },
    ],
    video: null,
  },
  {
    id: "game03",
    title: "NEON DRIFT",
    subtitle: "ドリフトでコースを走るレースゲーム",
    icon: "./assets/images/games/neon-drift.svg",
    iconAlt: "夕日の沈むネオンの街を走る、レトロなスポーツカーのイラスト",
    description: "ドリフトを使ってコースを走るレースゲームです。1レースは約3分で、自己ベストの更新を目指します。",
    genre: "レース",
    players: "1人",
    playTime: "約3分",
    platform: "Windows PC",
    creators: ["ゲーム制作チーム C"],
    team: "Midnight Studio",
    accent: "#f9e7ec",
    tip: "カーブの手前からドリフトを始めると曲がりやすくなります。",
    controls: [
      { device: "キーボード", items: [{ keys: ["W", "↑"], action: "アクセル" }, { keys: ["S", "↓"], action: "ブレーキ" }, { keys: ["A", "D", "←", "→"], action: "ハンドル" }, { keys: ["Space"], action: "ドリフト" }, { keys: ["Esc"], action: "ポーズ・メニュー" }] },
      { device: "ゲームパッド", items: [{ keys: ["RT"], action: "アクセル" }, { keys: ["LT"], action: "ブレーキ" }, { keys: ["左スティック"], action: "ハンドル" }, { keys: ["A ボタン"], action: "ドリフト" }, { keys: ["Menu"], action: "ポーズ・メニュー" }] },
    ],
    screenshots: [
      { src: "./assets/images/games/neon-drift-scene-1.svg", alt: "夕日に向かって伸びるネオンシティの直線コース", caption: "直線コース" },
      { src: "./assets/images/games/neon-drift-scene-2.svg", alt: "夜の高層ビルの間を駆け抜けるスポーツカー", caption: "街中のコース" },
    ],
    video: null,
  },
];
