/* サイトの名前と全作品をここで管理します。追加方法はREADME.mdを参照してください。 */
window.EXHIBITION = {
  name: "GAME LAB.",
  year: "2026",
  festivalName: "文化祭 ゲーム作品展",
  message: "気になることがあれば、会場のスタッフに声をかけてください。",
  sampleMode: true,
};

window.GAMES = [
  {
    id: "game01",
    title: "MOSSBOUND",
    subtitle: "小さな一歩が、森を目覚めさせる。",
    icon: "./assets/images/games/mossbound.svg",
    iconAlt: "光る森の遺跡にたたずむ、小さな白い旅人のイラスト",
    description: "忘れられた森に、もう一度いのちの光を。小さな旅人を操作して、苔に覆われた遺跡をめぐる2Dアクションゲームです。\n足場を飛び越え、森に眠る光のかけらを集めましょう。急がなくても大丈夫。あなただけのペースで、小さな冒険を楽しんでください。",
    genre: "アクション",
    players: "1人",
    playTime: "5〜10分",
    platform: "Windows PC",
    creators: ["ゲーム制作チーム A"],
    team: "Team Moss",
    accent: "#e3f1e7",
    tip: "まずは左右に動いてみよう。ジャンプ中も移動できるので、足場の端からゆっくり飛んでみてね。",
    controls: [
      { device: "キーボード", items: [{ keys: ["A", "D", "←", "→"], action: "左右に移動" }, { keys: ["Space"], action: "ジャンプ" }, { keys: ["E"], action: "調べる・話しかける" }, { keys: ["Esc"], action: "ポーズ・メニュー" }] },
      { device: "ゲームパッド", items: [{ keys: ["左スティック"], action: "左右に移動" }, { keys: ["A ボタン"], action: "ジャンプ" }, { keys: ["X ボタン"], action: "調べる・話しかける" }, { keys: ["Menu"], action: "ポーズ・メニュー" }] },
    ],
    screenshots: [
      { src: "./assets/images/games/mossbound-scene-1.svg", alt: "光る植物と大きな門がある、はじまりの森", caption: "01 — 光に導かれて、森の奥へ。" },
      { src: "./assets/images/games/mossbound-scene-2.svg", alt: "水面に浮かぶ足場と、光のかけらがある遺跡", caption: "02 — 小さなジャンプで、道を切り開く。" },
      { src: "./assets/images/games/mossbound-scene-3.svg", alt: "大樹の前で輝く光を見つけた旅人", caption: "03 — この森が、待っていたもの。" },
    ],
    video: { type: "local", src: "./assets/videos/mossbound-preview.mp4", poster: "./assets/images/games/mossbound-scene-1.svg", caption: "サンプル映像（6秒・音声なし）。オリジナルイラストによる展示イメージです。" },
  },
  {
    id: "game02",
    title: "ORBIT SHIFT",
    subtitle: "世界を回せば、答えが見える。",
    icon: "./assets/images/games/orbit-shift.svg",
    iconAlt: "紫の宇宙空間に浮かぶ、ミント色と白色の立方体のパズル",
    description: "見方を変えると、行き止まりが道になる。宇宙に浮かぶ不思議なステージを回転させ、ゴールを目指す立体パズルです。\nブロックのつながりを見つけて、小さなキューブを導いてください。ひらめいた瞬間の気持ちよさを、ぜひ体験してみてください。",
    genre: "パズル",
    players: "1人",
    playTime: "3〜5分",
    platform: "PC / スマートフォン",
    creators: ["ゲーム制作チーム B"],
    team: "Orbit Works",
    accent: "#eeebf8",
    tip: "行き詰まったら、ステージを回して別の角度から見てみよう。手数の制限はありません。",
    controls: [
      { device: "マウス", items: [{ keys: ["ドラッグ"], action: "ステージを回転" }, { keys: ["左クリック"], action: "行き先のブロックを選ぶ" }, { keys: ["右クリック"], action: "ひとつ前に戻る" }] },
      { device: "スマートフォン", items: [{ keys: ["スワイプ"], action: "ステージを回転" }, { keys: ["タップ"], action: "行き先のブロックを選ぶ" }, { keys: ["戻るボタン"], action: "ひとつ前に戻る" }] },
    ],
    screenshots: [
      { src: "./assets/images/games/orbit-shift-scene-1.svg", alt: "星空に浮かぶ立体パズルの最初のステージ", caption: "01 — 視点を変える、小さな宇宙。" },
      { src: "./assets/images/games/orbit-shift-scene-2.svg", alt: "離れた立方体をつないで進むパズルステージ", caption: "02 — つながる瞬間を、見つけよう。" },
    ],
    video: null,
  },
  {
    id: "game03",
    title: "NEON DRIFT",
    subtitle: "この夜を、駆け抜けろ。",
    icon: "./assets/images/games/neon-drift.svg",
    iconAlt: "夕日の沈むネオンの街を走る、レトロなスポーツカーのイラスト",
    description: "ネオンに染まる街を、ひと息で駆け抜ける。シンプルな操作でスピード感を楽しめる、アーケードスタイルのレースゲームです。\nカーブに合わせてドリフトを決め、自己ベストを更新しよう。1レースは約3分。ちょっとした時間に、全力の疾走を。",
    genre: "レース",
    players: "1人",
    playTime: "約3分",
    platform: "Windows PC",
    creators: ["ゲーム制作チーム C"],
    team: "Midnight Studio",
    accent: "#f9e7ec",
    tip: "カーブに入る少し前からドリフトすると曲がりやすくなります。まずは1周、コースを覚えてみよう。",
    controls: [
      { device: "キーボード", items: [{ keys: ["W", "↑"], action: "アクセル" }, { keys: ["S", "↓"], action: "ブレーキ" }, { keys: ["A", "D", "←", "→"], action: "ハンドル" }, { keys: ["Space"], action: "ドリフト" }, { keys: ["Esc"], action: "ポーズ・メニュー" }] },
      { device: "ゲームパッド", items: [{ keys: ["RT"], action: "アクセル" }, { keys: ["LT"], action: "ブレーキ" }, { keys: ["左スティック"], action: "ハンドル" }, { keys: ["A ボタン"], action: "ドリフト" }, { keys: ["Menu"], action: "ポーズ・メニュー" }] },
    ],
    screenshots: [
      { src: "./assets/images/games/neon-drift-scene-1.svg", alt: "夕日に向かって伸びるネオンシティの直線コース", caption: "01 — スタートラインの向こうへ。" },
      { src: "./assets/images/games/neon-drift-scene-2.svg", alt: "夜の高層ビルの間を駆け抜けるスポーツカー", caption: "02 — 光の中で、ベストを超える。" },
    ],
    video: null,
  },
];
